# Generated by Django 4.1.7 on 2023-03-24 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='day',
            field=models.DateField(default=datetime.date(2023, 3, 24)),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='name',
            field=models.CharField(default='Monday', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 24, 6, 4, 5, 77301)),
        ),
    ]
