# Generated by Django 4.1.7 on 2023-03-25 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_daymenu_day_alter_daymenu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='day',
            field=models.DateField(default=datetime.date(2023, 3, 25)),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 25, 12, 17, 34, 735671)),
        ),
    ]
