# Generated by Django 4.1.7 on 2023-03-26 15:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_alter_timemenu_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 26, 18, 20, 31, 919683)),
        ),
    ]
