# Generated by Django 4.1.7 on 2023-03-28 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_alter_daymenu_day_alter_timemenu_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='special_flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_category_images/', verbose_name='Special Flag Image (Only for Specials)'),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 28, 6, 45, 56, 409663)),
        ),
    ]
