# Generated by Django 4.1.7 on 2023-03-28 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0006_foodcategory_special_flag_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='This image will act as the background for the carousel for this category', null=True, upload_to='food_category_images/', verbose_name='Optional Image (Representative of the category)'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='special_flag_image',
            field=models.ImageField(blank=True, help_text='This image will act as the background for the carousel for this special', null=True, upload_to='food_category_images/', verbose_name='Optional Special Flag Image (Only for Specials)'),
        ),
        migrations.AlterField(
            model_name='timemenu',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 28, 7, 5, 30, 472408)),
        ),
    ]
